"""add cascade delete for retrieval_test_runs.test_set_id

Revision ID: 17b2dd965edb
Revises: 46e0b3c1966b
Create Date: 2026-09-11 16:04:30.401147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17b2dd965edb'
down_revision: Union[str, Sequence[str], None] = '46e0b3c1966b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('retrieval_test_runs_test_set_id_fkey'), 'retrieval_test_runs', type_='foreignkey')
    op.create_foreign_key(None, 'retrieval_test_runs', 'retrieval_test_sets', ['test_set_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'retrieval_test_runs', type_='foreignkey')
    op.create_foreign_key(op.f('retrieval_test_runs_test_set_id_fkey'), 'retrieval_test_runs', 'retrieval_test_sets', ['test_set_id'], ['id'])
    # ### end Alembic commands ###
