"""model_configs

Revision ID: 48f47d6eefe4
Revises: 712d1f20d472
Create Date: 2026-08-09 10:20:56.167369
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '48f47d6eefe4'
down_revision = '712d1f20d472'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_configs',
    sa.Column('grp', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('prov', sa.String(length=32), nullable=False),
    sa.Column('use', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('api_key_enc', sa.Text(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grp', 'name', name='uq_model_grp_name')
    )
    op.create_index(op.f('ix_model_configs_grp'), 'model_configs', ['grp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_configs_grp'), table_name='model_configs')
    op.drop_table('model_configs')
    # ### end Alembic commands ###
