"""add dead_letter_tasks table

Revision ID: 67d2716c50c5
Revises: 5a3cc27e2156
Create Date: 2026-09-10 14:30:48.753974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67d2716c50c5'
down_revision: Union[str, Sequence[str], None] = '5a3cc27e2156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dead_letter_tasks',
    sa.Column('task_id', sa.String(length=100), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('args', sa.Text(), nullable=True),
    sa.Column('kwargs', sa.Text(), nullable=True),
    sa.Column('exception', sa.Text(), nullable=False),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('retried_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retried_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_letter_tasks_status'), 'dead_letter_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_dead_letter_tasks_task_id'), 'dead_letter_tasks', ['task_id'], unique=True)
    op.create_index(op.f('ix_dead_letter_tasks_task_name'), 'dead_letter_tasks', ['task_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dead_letter_tasks_task_name'), table_name='dead_letter_tasks')
    op.drop_index(op.f('ix_dead_letter_tasks_task_id'), table_name='dead_letter_tasks')
    op.drop_index(op.f('ix_dead_letter_tasks_status'), table_name='dead_letter_tasks')
    op.drop_table('dead_letter_tasks')
    # ### end Alembic commands ###
