"""chunks

Revision ID: f9a68189a76d
Revises: dd79b9b9b651
Create Date: 2026-08-09 15:05:51.963581
"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


revision = 'f9a68189a76d'
down_revision = 'dd79b9b9b651'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunks',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('kb_id', sa.String(length=36), nullable=False),
    sa.Column('clause_title', sa.String(length=255), nullable=True),
    sa.Column('section_path', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_search', sa.Text(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('element_count', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('embedding', Vector(dim=1024), nullable=True),
    sa.Column('embedding_model', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_chunks_kb_id'), 'chunks', ['kb_id'], unique=False)
    # 向量近似检索索引（余弦）
    op.execute("CREATE INDEX IF NOT EXISTS idx_chunk_embedding ON chunks USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)")
    # 全文模糊检索索引（pg_trgm）
    op.execute("CREATE INDEX IF NOT EXISTS idx_chunk_trgm ON chunks USING gin (content_search gin_trgm_ops)")
    # 按文档+页码检索（元素定位/翻页）
    op.execute("CREATE INDEX IF NOT EXISTS idx_chunk_doc_page ON chunks (document_id, page_number)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS idx_chunk_doc_page")
    op.execute("DROP INDEX IF EXISTS idx_chunk_trgm")
    op.execute("DROP INDEX IF EXISTS idx_chunk_embedding")
    op.drop_index(op.f('ix_chunks_kb_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_table('chunks')
    # ### end Alembic commands ###
